### ISSUE TITLE
vcd_vapp_vm_disk - disk creation is not idempotent

### ISSUE THREAD

**Issue by IAmAnthem** [vmware/ansible-module-vcloud-director#100]
Thanks for quick response to issue 99!  I'm having a lot of fun with these modules.

VM Disk "present" should be idempotent if I specify a disk_name

```

tasks:
- name:
  vcd_vapp_vm_disk:
    vm_name: myVM
    vapp: myVapp
    vdc: myvDC
    disk_name: "Hard Disk 3"
    size: 100
    state: "present"'

```

This produces a new disk each time it is run.  the disk_name is not checked for existence, and ignored in the creation of a new disk.

So when I ran that play 3 times, I got 3 new disks added!
