### ISSUE TITLE
Allow External Network creation with Portgroup ID as well as Portgroup Name

### ISSUE THREAD

**Issue by surfer190** [vmware/ansible-module-vcloud-director#104]
It is difficult to get the portgroup name from the NSX API.

I think it would be worthwhile to allow adding of portgroups using their id's.

**Comment by mukultaneja** [comment]
@surfer190, can you not try to fetch port groups from vCenter REST APIs or MOB?

**Comment by surfer190** [comment]
@mukultaneja I can get a [list of networks from vcenter](https://vdc-download.vmware.com/vmwb-repository/dcr-public/423e512d-dda1-496f-9de3-851c28ca0814/0e3f6e0d-8d05-4f0c-887b-3d75d981bae5/VMware-vSphere-Automation-SDK-REST-6.7.0/docs/apidocs/operations/com/vmware/vcenter/network.list-operation.html) but then have to pattern match to find the one I need.

Is there a way to get the portgroup name if you only have the subnet or virtual-wire (logical switch) id?

**Comment by mukultaneja** [comment]
I think port groups and logical switches are two different things and what do you mean by pattern matching here as the API which you referred should give you the name of the port group.

**Comment by mukultaneja** [comment]
@surfer190, were you able to resolve your issue?

**Comment by surfer190** [comment]
Yes. I did as you suggested. 

```
  - name: Find out the name of the portgroup for the logical switch in NSX
    uri:
      url: "{{ NSX_URL }}/api/2.0/vdn/virtualwires/{{ virtual_wire }}"
      return_content: yes
      method: 'GET'
      body_format: 'json'
      headers:
        Accept: "application/json"
    register: virtual_wire_result
  
  - name: Set the portgroup fact
    set_fact:
      port_group: "{{ virtual_wire_result.json.backing.0.backingValue }}"
  
  - name: Login into vCenter and get cookies
    uri:
      ...

  - name: Find the portgroup name from the id in vcenter
    uri:
      url: "{{ vcenter_server }}/rest/vcenter/network?filter.networks={{ port_group }}"
      method: 'GET'
      body_format: 'json'
      return_content: yes
      headers:
        Cookie: "{{ login.set_cookie }}"
    register: vcenter_portgroup_result
  
  - name: Set the portgroup name
    set_fact:
      portgroup_name: "{{ vcenter_portgroup_result.json.value.0.name }}"
```

Thanks.
