### ISSUE TITLE
vcd_vapp_vm_nic UPDATE or ABSENT act unexpectedly.

### ISSUE THREAD

**Issue by IAmAnthem** [vmware/ansible-module-vcloud-director#119]
Building up some demonstrations, I'm cloning a template VM and NOT setting a network at that time.  Turns out, if you do that, something in the code can't figure out what NIC you're trying to talk to.

I don't understand the error message I'm getting when I try to update a NIC.

Next I tried adding a NIC, and got back NIC 0 with no network, and NIC 1 with the network I wanted.

Thought I'd just add a step that deletes NIC 0 first, I tried to set it to ABSENT, and ansible says it can't find that NIC.

Code:
```
- name: Modify NIC 0 and connect to vApp Network
  no_log: False
  vcd_vapp_vm_nic:
    network: "{{ vAppNetworkName }}"
    vm_name: "{{ item }}"
    vdc: "{{ myvDC }}"
    vapp: "{{ myvApp }}"
    ip_allocation_mode: POOL
    adapter_type: VMXNET3
    nic_ids: 0
    state: update
  with_items: "{{ VMLIST }}"
  register: output
```

DEBUG MODE:
```
ok: [localhost] => (item=POC-DC-01) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "adapter_type": "VMXNET3",
            "api_version": "31.0",
            "host": "https://OMITTED",
            "ip_address": null,
            "ip_allocation_mode": "POOL",
            "is_connected": false,
            "is_primary": false,
            "network": "POC-Servers-Net",
            "nic_ids": [
                "0"
            ],
            "operation": null,
            "org": "OMITTED",
            "password": "OMITTED",
            "state": "update",
            "user": "OMITTED",
            "vapp": "Ansible-PoC",
            "vdc": "OMITTED",
            "verify_ssl_certs": false,
            "vm_name": "POC-DC-01"
        }
    },
    "item": "POC-DC-01",
    "msg": "Vapp with name 'POC-Servers-Net' not found."
}
```

Why does it think it's trying to find a vApp named "POC-Servers-Net" in the error message?
In the debug log above, the vApp is "Ansible-PoC"

Update:
This works IF I assign a network during VM deploy.  
The NIC Update documentation should specify a NIC must both exist, and be assigned to a network.  Or figure out why those are required and fix it :)

My playbook works the way I want it, but it could confuse someone else too...
