### ISSUE TITLE
vcd_vapp_vm does not support ip_allocation_mode MANUAL and ip_address

### ISSUE THREAD

**Issue by IAmAnthem** [vmware/ansible-module-vcloud-director#120]
For an environment where a vars file is provided identifying VM name and required IP address, I'd like to just build my VMs with that information.  DHCP is NOT AVAILABLE.

```
---
- name: touch my VMs
  hosts: localhost
  vars_files:
    - ./vars/credentials.yml
    - ./vars/main.yml

  environment:
    env_user: "{{ UserName }}"
    env_password: "{{ Password }}"
    env_host: "{{ Host }}"
    env_org: "{{ Org }}"
    env_api_version: 31.0
    env_verify_ssl_certs: "false"

  vars:
    VMLIST:
      - name: "{{ domainName }}-TINY-01"
        ip: 192.168.111.102
      - name: "{{ domainName }}-TINY-02"
        ip: 192.168.111.103


  tasks:
  - name: Create VMs from Template W19
    no_log: False
    vcd_vapp_vm:
      target_vm_name: "{{ item.name }}"
      target_vapp: "{{ myvApp }}"
      source_vdc: "{{ myvDC }}"
      target_vdc: "{{ myvDC }}"
      source_catalog_name: "{{ myCatalog }}"
      source_template_name: "{{ myTemplate }}"
      source_vm_name: "{{ myTemplateVM }}"
      hostname: "{{ item.name }}"
      network: "{{ VMHW.SmallVM.network }}"
      ip_allocation_mode: MANUAL
      cust_script: "{{ VMHW.SmallVM.cust_script }}"
      storage_profile: "{{ VMHW.SmallVM.storage_profile }}"
      virtual_cpus: "{{ VMHW.SmallVM.virtual_cpus }}"
      cores_per_socket: "{{ VMHW.SmallVM.cores_per_socket }}"
      memory: "{{ VMHW.SmallVM.memory }}"
      all_eulas_accepted: "{{ VMHW.SmallVM.all_eulas_accepted }}"
      state: "present"
      power_on: "false"
    with_items: "{{ VMLIST }}"
    register: output
```

Verbose error output:

```
Traceback (most recent call last):
  File \"/tmp/ansible_vcd_vapp_vm_payload_cr9zl_fh/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 354, in add_vm
  File \"/tmp/ansible_vcd_vapp_vm_payload_cr9zl_fh/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 329, in get_vm
  File \"/home/OMITTED/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp.py\", line 659, in get_vm
    raise EntityNotFoundException('Can\\'t find VM \\'%s\\'' % vm_name)
pyvcloud.vcd.exceptions.EntityNotFoundException: Can't find VM 'POC-TINY-01'
```
