### ISSUE TITLE
vcd_vapp_vm_disk, not creating disk

### ISSUE THREAD

**Issue by danielc256** [vmware/ansible-module-vcloud-director#137]
Hello,

I'm trying to add a new disk in a VM, see my task below:

![image](https://user-images.githubusercontent.com/67828229/93724945-35dae380-fba3-11ea-93b5-b1fb4f644bf5.png)

Traceback:
![image](https://user-images.githubusercontent.com/67828229/93515965-4e3bcb80-f921-11ea-9dfa-e49478edeade.png)

Note: Sorry for the print, and the bad quality, I'm in a datacenter with very limited access.
Note2: Ignore the SSL error, I'm not checking SSL certificate in my playbook.

It says at the end "add_disk_to_vm() takes 3 positional arguments but 4 were given\r\n"   (Why?)

I'm using Python 3.6.8 and pyvcloud 22.0.1 on RHEL8
My target is vCloud 9.7, API 32.0

**Comment by 387119** [comment]
same issue

**Comment by mukultaneja** [comment]
@387119 Please use [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Disk) for module usage.. I am going to remove the `doc` directory soon and continue using the wiki.

@danielc256 The code is working fine with VCD 10.0. please give me a day or two to validate it on VCD 9.7 as well.

**Comment by mukultaneja** [comment]
@387119 @danielc256, Apologies to reply late. I looked into the issue and the current module code is working fine as expected on VCD 9.7 with API Version 30.0, 31.0, 32.0. This issue might be coming because you guys are using Pyvcloud release [22.0.1](https://github.com/vmware/pyvcloud/releases/tag/22.0.1) which was released on 1 Apr 2020 whereas I updated the existing  [add_disk_to_vm](https://github.com/vmware/pyvcloud/commit/ab648b013209127ba02dad24b0edb04d392fdfd7) on 21 Apr 2020. So a possible solution could be a manual update of Pycloud or we can wait until a new release from Pyvcloud comes up. Please let me know if it is possible for you to update Pyvcloud manually, I can help you to update.

**Comment by danielc256** [comment]
Hello @mukultaneja, I can update.

But I see that on pypi.org the latest version of pyvcloud is 22.0.1, what's this new version you're saying and how to perform the update?

**Comment by mukultaneja** [comment]
@danielc256, Please try to install a dev version of Pyvcloud using `pip install pyvcloud==22.0.2.dev32` and let me know if it works well.

**Comment by 387119** [comment]
@mukultaneja Thanks for solution, unfotunatelly I cannot confirm 100% that it`s working, but I assume it is,

due to I have old (27.0) version of vcloud director, and this API version does not provide feature to add disks.

error I receiving now.
TypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.BadRequestException'>, Status code: 400/BAD_REQUEST, Bad request  - Unexpected JAXB Exception  - cvc-comple
x-type.2.4.a: Invalid content was found starting with element 'rasd:ResourceSubType'. One of '{"http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSetti
ngData":Weight, WC[##other:"http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData"]}' is expected. (request id: 986fd177-caf8-4c10-b3ce-079df31
6e04e)

so from my side I don`t have any concerns to this issue, I think it can be closed with response something like "use 22.0.2+ or 22.0.2.dev32" with API >... (I'm not sure about minimal required API version)

**Comment by mukultaneja** [comment]
@387119 I am not sure about this error but I can add a new disk to a VM deployed in VCD 9.7 with below configs,

Pyvcloud == 22.0.1.dev31
VCD API Version == 27.0

<img width="1589" alt="Screenshot 2020-10-14 at 1 18 45 AM" src="https://user-images.githubusercontent.com/16931639/95909132-997bb980-0dbb-11eb-8506-33585bcaf94e.png">

**Comment by 387119** [comment]
@mukultaneja could you please share your ansible code for task "vcd_vapp_vm_disk : add a disk"

**Comment by 387119** [comment]
I`ve used next syntax
```
- name: Create additional disks
  vcd_vapp_vm_disk:
     vm_name: "{{ item }}"
     vapp: "{{ target_vapp }}"
     vdc: "{{ target_vdc }}"
     disks:
       - size: "100000"
          controller: "lsilogic"
    state: "present"
  loop: "{{ rh7docker }}"
```

**Comment by 387119** [comment]
so finally my issue was with syntax, next code works for me

```
- name: Create additional disks
vcd_vapp_vm_disk:
   vm_name: "{{ item }}"
     vapp: "{{ target_vapp }}"
     vdc: "{{ target_vdc }}"
     disks:
        - size: 100000
           controller: VirtualSCSI
     state: "present"
  loop: "{{ rh7docker }}"
```
```
TASK [Create additional disks] **********************************************************************************************************************************************
changed: [localhost] => (item=rh7docker01)
```
