### ISSUE TITLE
Role 'Organization Administrator' does not exist.

### ISSUE THREAD

**Issue by surfer190** [vmware/ansible-module-vcloud-director#139]
When creating a user with the `Organization Administrator` role I get the following error:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.EntityNotFoundException'>, Role 'Organization Administrator' does not exist.`

Note that this only happens on lab infrastructure. It works on other envrionements.

The task is:

```
  - name: Create org admin
    vcd_user:
      org_name: "STP001"
      username: "admin"
      userpassword: "xxx"
      role_name: "Organization Administrator"
      full_username: "Administrator"
      description: "STP001 Administrator"
      email: "surfer190@gmail.com"
      is_enabled: "true"
      state: "present"
      is_external: "false"
```

I can create the user with a seperate soap request to the api directly.

How can I debug and see what the real response it from the api?
