### ISSUE TITLE
Add additional VM disk if not exist

### ISSUE THREAD

**Issue by 387119** [vmware/ansible-module-vcloud-director#140]
https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Disk

is there a simple way to add additional drive only in case it does not exist.

example: I have only /dev/sda in template, I need /dev/sdb, as per instruction I create additional drive using next code
```
- name: Create additional disks
vcd_vapp_vm_disk:
 vm_name: "{{ item }}"
  vapp: "{{ target_vapp }}"
  vdc: "{{ target_vdc }}"
  disks:
    - size: 100000
      controller: VirtualSCSI
  state: "present"
loop: "{{ rh7docker }}"
```

this code will add additional drive sdb, sdc, sdd, ... each execution, 

probably "name" can help me, but I don`t see such option in wiki for state: "present" which is required for create drive

**Comment by 387119** [comment]
next block works fine, but finally do the same, create additional drive each execution
```
- name: Create additional disks
vcd_vapp_vm_disk:
 vm_name: "{{ item }}"
  vapp: "{{ target_vapp }}"
  vdc: "{{ target_vdc }}"
  disks:
    - name: 'Hard disk 1'
    - size: 100000
      controller: VirtualSCSI
  state: "present"
loop: "{{ rh7docker }}"
```
I`ve tried names: 'Hard disk 1', 'Disk 1', no luck
![image](https://user-images.githubusercontent.com/44392341/96094708-5a8e5680-0ed6-11eb-9c71-fee8925e03be.png)
