### ISSUE TITLE
Create VMs and assign a static IP

### ISSUE THREAD

**Issue by rthomson** [vmware/ansible-module-vcloud-director#15]
Thanks for supporting ansible users with these provisioning modules, VMware!

I'm wondering how one would go about creating multiple VMs within a vApp, each assigned their own static IP address using this project?

The only module that appears to support setting a static/manual IP address is `vcd_vapp`. However, I can't seem to use this module multiple times targeting the same vApp with different/separate VMs as the module tells me the "vApp is already present" when I run it after the first subsequent run where it creates the vApp and VM.

The `vcd_vapp_vm` module has `ip_allocation_mode` but no `ip_address` attribute.

Am I missing something or does this functionality not yet exist?

**Comment by carmineesposito73** [comment]
any news on this enhancement? it would be very useful
thanks

**Comment by sgutermann** [comment]
I second that. Would definately be usefull.

**Comment by mukultaneja** [comment]
@rthomson, please use vappvmnic module to assign static IPs to the VM and acknowledge if it works for you.

**Comment by carmineesposito73** [comment]
@rthomson @mukultaneja with the new `vcd_vapp_vm_nic` to create a vm with nic0 with a static address you have to:

- create the vm (in my use case I have a vm with nic0 with dhcp)
- add a vm nic (should be nic1)
- delete nic0
- add a vm nic (should be nic0)
- delete nic1

you cannot add a nic to a vm without any nics (the NetworkConnectionSection is not present in vms without nics)

**Comment by sgutermann** [comment]
@carmineesposito73 thank you for posting that. I though I was going crazy. I had to make a template with a nic connection in order to get creating VMs. I was not able to get a template running and adding a nic to it afterwards.

Funny enough that does work using the HTML5 Client. So IMO there must be a way.

**Comment by mukultaneja** [comment]
@all, I have updated vcd_vapp_vm_nic module with update functionality of VM NICs. As of now, you can switch between Manual to DHCP mode and update NIC's Ip Address in Manual mode. Update me if I have covered me this enhancement.

**Comment by carmineesposito73** [comment]
@mukultaneja, I tested the new module: i can switch between all allocation modes: DHCP, POOL and MANUAL and I can change IP address in MANUAL mode.
Changing the network is not covered, right?

**Comment by carmineesposito73** [comment]
here https://github.com/carmineesposito73/ansible-module-vcloud-director/blob/master/modules/vcd_vapp_vm_nic.py you can find my proposal on this modules:
* added nic_id parameter to create a nic with id chosen by the user (can be useful, for example, if you like to have, on different vms, the same nic id on a specific network, e.g nic_id = 9 on network "mgmt")
* update operation can be done even if network change is needed

**Comment by mukultaneja** [comment]
@carmineesposito73 network is also covered!

**Comment by carmineesposito73** [comment]
@mukultaneja, I had errors, I'll do more tests

**Comment by carmineesposito73** [comment]
@mukultaneja, I got an exception trying to change network.
```
Value of unknown type: <class 'pyvcloud.vcd.exceptions.BadRequestException'>, Status code: 400/BAD_REQUEST, Bad request  - Unexpected JAXB Exception  - cvc-complex-type.2.4.d: Invalid content was found starting with element 'network'. No child element is expected at this point. (request id: 573f3815-7141-4be9-b97e-0eb036b1805b)\r\n", 
```

To simplify I tried to change network of a DHCP nic, I've done this tests

```
  tasks:
  - name: update vm nic
    vcd_vapp_vm_nic:
        vm_name: "{{ my_vm }}"
        vapp: "{{ my_vapp }}"
        vdc: "{{ my_vdc }}"
        network: "{{ my_network }}"
        #ip_allocation_mode: "{{ my_ip_mode }}"
        nic_id: "{{ my_nic_id }}"
        operation: "update"
```
```
  tasks:
  - name: update vm nic
    vcd_vapp_vm_nic:
        vm_name: "{{ my_vm }}"
        vapp: "{{ my_vapp }}"
        vdc: "{{ my_vdc }}"
        network: "{{ my_network }}"
        ip_allocation_mode: "{{ my_ip_mode }}"
        nic_id: "{{ my_nic_id }}"
        operation: "update"
```
