### ISSUE TITLE
Unable to create firewall rules

### ISSUE THREAD

**Issue by Sher-Chowdhury** [vmware/ansible-module-vcloud-director#165]
I can't seem to create new firewall rules, here's what my playbook looks like:

```
---
- name: vCloudDirectorAnsible
  hosts: localhost
  gather_facts: no
  environment:
    env_user: admin
    env_password: xxxxx
    env_host: xxxxxx.com
    env_org: xxxxxx 
    env_api_version: 34.0
    env_verify_ssl_certs: false


  tasks:

    - name: list gateway firewalls
      vcd_gateway_services:
        org: xxxxxx
        vdc: sher1
        gateway: xxxxxxxxxxx
        service: firewall
        operation: list
      register: output

    - name: list of firewalls rules
      debug:
        msg: '{{ output }}'



    - name: create gateway services
      vcd_gateway_services:
        org: xxxxx
        vdc: sher1
        gateway: xxxxxx
        service: firewall
        service_params:
            - name: test_firewall
              action: accept
              type: User
              enabled: True
              logging_enabled: False
              source_values:
                - ip:
                    - "192.168.110.102-192.168.110.115"
              destination_values:
                - gatewayinterface:
                    - "Any"
              services:
                - tcp:
                    source_port: any
                    destination_port: any
        state: present
      register: output
```

This outputs:

```
$ ansible --version
ansible 2.10.4
  config file = /Users/sherchowdhury/tmp/ansible/vmware/ansible-module-vcloud-director/ansible.cfg
  configured module search path = ['/Users/sherchowdhury/tmp/ansible/vmware/ansible-module-vcloud-director/modules']
  ansible python module location = /Users/sherchowdhury/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /Users/sherchowdhury/Library/Python/3.8/bin/ansible
  python version = 3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39) [Clang 6.0 (clang-600.0.57)]

$ ansible-playbook main.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [vCloudDirectorAnsible] ***********************************************************************************************************************************************************************************

TASK [list gateway firewalls] **********************************************************************************************************************************************************************************
ok: [localhost]

TASK [list of firewalls rules] *********************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "msg": [
            {
                "id": 131074,
                "name": "firewall",
                "type": "internal_high"
            },
            {
                "id": 131075,
                "name": "highAvailability",
                "type": "internal_high"
            },
            {
                "id": 131076,
                "name": "dns",
                "type": "internal_high"
            },
            {
                "id": 131073,
                "name": "default rule for ingress traffic",
                "type": "default_policy"
            }
        ]
    }
}

TASK [create gateway services] *********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Traceback (most recent call last):\n  File \"/var/folders/_g/mzkyjqvs1wx8jyl_n6fxsp7m0000gn/T/ansible_vcd_gateway_services_payload_iyeuqgqz/ansible_vcd_gateway_services_payload.zip/ansible/module_utils/gateway_firewall_service.py\", line 100, in add\n    self.get_firewall_rule(name)\n  File \"/var/folders/_g/mzkyjqvs1wx8jyl_n6fxsp7m0000gn/T/ansible_vcd_gateway_services_payload_iyeuqgqz/ansible_vcd_gateway_services_payload.zip/ansible/module_utils/gateway_firewall_service.py\", line 37, in get_firewall_rule\n    raise EntityNotFoundException(msg.format(fw_rule_name))\npyvcloud.vcd.exceptions.EntityNotFoundException: Firewall rule test_firewall does not exists\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/folders/_g/mzkyjqvs1wx8jyl_n6fxsp7m0000gn/T/ansible_vcd_gateway_services_payload_iyeuqgqz/ansible_vcd_gateway_services_payload.zip/ansible/module_utils/gateway_firewall_service.py\", line 107, in add\n    self.update([service_param])\n  File \"/var/folders/_g/mzkyjqvs1wx8jyl_n6fxsp7m0000gn/T/ansible_vcd_gateway_services_payload_iyeuqgqz/ansible_vcd_gateway_services_payload.zip/ansible/module_utils/gateway_firewall_service.py\", line 142, in update\n    firewall_rule.edit(source_values=source_values,\n  File \"/Users/sherchowdhury/Library/Python/3.8/lib/python/site-packages/pyvcloud/vcd/firewall_rule.py\", line 95, in edit\n    self._populate_objects_info(firewall_rule_temp, destination_values,\n  File \"/Users/sherchowdhury/Library/Python/3.8/lib/python/site-packages/pyvcloud/vcd/firewall_rule.py\", line 163, in _populate_objects_info\n    firewall_rule_temp.destination.append(\nTypeError: Argument 'element' has incorrect type (expected lxml.etree._Element, got NoneType)\n"}

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by mukultaneja** [comment]
@Sher-Chowdhury, it is failing because you can't use `Any` as a value for `gatewayinterface` object type. It must be having a value of network interface present in the system. However, I just added a patch that allows you to create a firewall without a source or destination value [ means with `any` support]. With the latest patch, you can use the below play to create a firewall.
```
     service_params:
        - name: test_firewall
          action: accept
          type: User
          enabled: True
          logging_enabled: False
          source_values:
            - any:
                - any
          destination_values:
            - any:
                - any
          services:
            - tcp:
                source_port: any
                destination_port: any
        - name: test_firewall_2
          action: accept
          type: User
          enabled: True
          logging_enabled: False
          source_values:
            - ip:
                - "192.168.110.102-192.168.110.115"
          destination_values:
            - gatewayinterface:
                - "external-network-3"
          services:
            - tcp:
                source_port: any
                destination_port: any
     state: present
  register: output
```
try it out once and let me know if it was helpful!
