### ISSUE TITLE
Cannot create catalog with vcd admin user

### ISSUE THREAD

**Issue by TheEric7** [vmware/ansible-module-vcloud-director#172]
Can't create a catalog with vCloud Director's Admin user which has access to all organizations.
My playbook is:
```
---
- name: create catalog
  hosts: localhost
  environment:
    env_user: my_user
    env_password: my_password
    env_host: my_host
    env_org: system
    env_api_version: 30.0
    env_verify_ssl_certs: false
  tasks:
  - name: create catalog
    vcd_catalog:
      catalog_name: "test"
      description: "test"
      state: "present"
```

And the expected error is **"Status code: 400/BAD_REQUEST, No storage available in the organization. Please allocate resources to your organization.** This is understandable because the catalog should be created on an organization other than system. But when I add the org name it says can't login to the organization with that user, even though that user is Admin and has access to every organization.

```
---
- name: create catalog
  hosts: localhost
  environment:
    env_user: my_user
    env_password: my_password
    env_host: my_host
    env_org: system
    env_api_version: 30.0
    env_verify_ssl_certs: false
  tasks:
  - name: create catalog
    vcd_catalog:
      catalog_name: "test"
      description: "test"
      state: "present"
      org: "my-org"    <<<<<<<
```
And the error is:
**"Login failed for user my_user to org my-org"**

Note that I'm able to work with some other modules without issues this way. i.e.
```
---
- name: create org vdc direct network
  environment:
    env_user: my_user
    env_password: my_password
    env_host: my_host
    env_org: system
    env_api_version: 30.0
    env_verify_ssl_certs: false
  tasks:
  - name: create network
    vcd_vdc_network:
      org_name: test-org
      vdc_name: test-vdc
      network_name: test-network
      parent_network_name: test-network
      shared: false
      direct: true
      state: present
```
