### ISSUE TITLE
Deleting an org fails with 'dict' object has no attribute 'update_org'

### ISSUE THREAD

**Issue by surfer190** [vmware/ansible-module-vcloud-director#180]
I get an error: `AttributeError: 'dict' object has no attribute 'update_org'`. 

```
  - name: delete org
     vcd_org:
       org_name: "{{ org_name }}"
       force: "true"
       recursive: "true"
       state: "absent"
```

VCD version: `VMware Cloud Director version: 10.2.1.17444397`
