### ISSUE TITLE
Deny or disable existing firewall rule not working

### ISSUE THREAD

**Issue by rkadirbaks** [vmware/ansible-module-vcloud-director#183]
Hi,   

Updating an existing firewall rule in disable/deny the rule, doesn't work.   
The firewall rule remains enabled/allowed.   

This is how the service_params section in my playbook looks like;   

```
.....
    service: firewall
    service_params:
      - name: test_1
        enabled: False (also tried action: deny)
    state: update
  register: output
.....
```

Ansible output says it made the changes, but the fw rule remains enabled/allowed in vcloud director.   
{
  "msg": {
    "changed": true,
    "msg": "Firewall rule(s) ['test_1'] have been updated",
    "failed": false
  },

I will appreciate it, if you could please help me with this.   

Cheers
