### ISSUE TITLE
Expecting property name enclosed in double quotes -- vcd_org_vdc

### ISSUE THREAD

**Issue by MichalTaratuta** [vmware/ansible-module-vcloud-director#19]
I'm getting this error for the `storage_profiles` param:

```
The full traceback is:
  File "/tmp/ansible_vcd_org_vdc_payload_cpdcvfxd/__main__.py", line 369, in main
    response = module.manage_states()
  File "/tmp/ansible_vcd_org_vdc_payload_cpdcvfxd/__main__.py", line 246, in manage_states
    return self.create()
  File "/tmp/ansible_vcd_org_vdc_payload_cpdcvfxd/__main__.py", line 260, in create
    storage_profiles = json.loads(self.params.get('storage_profiles'))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allocation_model": "AllocationPool",
            "api_version": "31.0",
            "cpu_allocated": 5,
            "cpu_limit": 0,
            "cpu_units": "GHz",
            "description": "DESCRIPTION",
            "host": "lab01vcd01.local",
            "is_enabled": true,
            "is_thin_provision": true,
            "mem_allocated": 4096,
            "mem_limit": 0,
            "mem_units": "MB",
            "network_pool_name": null,
            "network_quota": 0,
            "nic_quota": 0,
            "org": "Ansible",
            "org_name": "",
            "over_commit_allowed": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider_vdc_name": "CLOUDLAB PROVIDER VDC",
            "resource_guaranteed_cpu": 1.0,
            "resource_guaranteed_memory": 1.0,
            "state": "present",
            "storage_profiles": "[{'default': 'True', 'limit': '10', 'enabled': 'true', 'units': 'GB', 'name': 'GOLD TIER'}]",
            "user": "John_Ansible",
            "uses_fast_provisioning": true,
            "vcpu_in_mhz": null,
            "vdc_name": "Ansible Allocation Pool",
            "verify_ssl_certs": false,
            "vm_discovery_enabled": null,
            "vm_quota": 0
        }
    },
    "msg": "Expecting property name enclosed in double quotes: line 1 column 3 (char 2)"
}
```

My task:
```yaml
- name: oVDC | Allocation Pool
  vcd_org_vdc:
    user: "{{vcd_user}}"
    password: "{{vcd_password}}"
    host: "{{host}}"
    org: "{{customer_org}}"
    api_version: "{{api_version}}"
    verify_ssl_certs: False
    vdc_name: "Ansible Allocation Pool"
    provider_vdc_name: "CLOUDLAB PROVIDER VDC"
    description: "DESCRIPTION"
    allocation_model: "AllocationPool"
    cpu_units: "GHz"
    cpu_allocated: 5
    cpu_limit: "0"
    mem_units: "MB"
    mem_allocated: 4096
    mem_limit: "0"
    nic_quota: "0"
    network_quota: "0"
    vm_quota: "0"
    storage_profiles:
      [{
      "name": "GOLD TIER",
      "enabled": "true",
      "units": "GB",
      "limit": "10",
      "default": "True"
    }]
    is_thin_provision: True
    uses_fast_provisioning: True
    is_enabled: "true"
    state: "present"
```

1. I have tried different syntax versions of `storage_profiles` and can't get this working.  What is the exact format for it, can you provide example rather then `List of provider vDC storage profiles to add to this vDC. Each item is a dictionary`.

2. `enabled` and `default` are those strings or booleans?
