### ISSUE TITLE
Can't taking a Vapp Snapshot

### ISSUE THREAD

**Issue by ebilly-ops** [vmware/ansible-module-vcloud-director#193]
I'm trying to take a snapshot of my Vapp but in the ansible task, we need to specify vm(s) name(s) and thus, it will take a snapshot per vm instead of taking a snapshot of the whole Vapp.

```
- name: create vm snapshot
  vcd_vapp_vm_snapshot:
    vdc_name: REDACTED
    vapp_name: REDACTED
    vms:
      - name: REDACTED
        mem_snapshot: false
      - name: REDACTED
        mem_snapshot: false
    state: present
  register: output
```

```
ok: [localhost] => {
    "msg": {
        "changed": false,
        "failed": false,
        "msg": [
            {
                "snapshot": {
                    "created": "2021-08-10T09:25:33.844Z",
                    "poweredOn": "false",
                    "size": "100.0 GB"
                },
                "vm_name": "REDACTED"
            },
            {
                "snapshot": {
                    "created": "2021-08-10T09:24:53.024Z",
                    "poweredOn": "false",
                    "size": "100.0 GB"
                },
                "vm_name": "REDACTED"
            }
        ]
    }
}
```

Anyone have a solution to take a real Vapp Snapshot ?
