### ISSUE TITLE
vCD-vApp-VM get-metadata only returns one entry

### ISSUE THREAD

**Issue by pille** [vmware/ansible-module-vcloud-director#220]
### Describe the bug

the task
```
    - name: get vApp VM metadata
      delegate_to: localhost
      vcd_vapp_vm:
        operation: "get_meta"
        target_vm_name: "{{ vcd_vm_name }}"
        target_vdc: "{{ vcd_vdc }}"
        target_vapp: "{{ vcd_vapp }}"
```
will only return one metadata entry, even if there are more.
it fails, when none is available.
documentation is also buggy, as it states one should use  `vcd_vapp`-module.

### Reproduction steps

see above

### Expected behavior

return all entries and don't fail when none is available.
also c'n'p failure in docs should be fixed.
