### ISSUE TITLE
unable to delete nic per docs

### ISSUE THREAD

**Issue by tfiedler** [vmware/ansible-module-vcloud-director#49]
I was getting errors when trying to delete a nic per the [docs](https://github.com/vmware/ansible-module-vcloud-director/blob/master/docs/index.md#delete-vapp-vm-nic) 

but when I started poking around I saw you could use a list nic_ids instead of a string nic_id and everything worked as expected.

```yaml
tasks:
    - name: Remove nic 0
      vcd_vapp_vm_nic:
          vm_name: "ansible-01"
          vapp: "ansible-01"
          vdc: "myVDC"
          nic_ids: [ 0 ]
          state: "absent"
```
Ted
