### ISSUE TITLE
Adding more than 1 network to a vapp?

### ISSUE THREAD

**Issue by tfiedler** [vmware/ansible-module-vcloud-director#50]
So I have this snippet
```yaml
- name: add ( update ) vapp with second network
      vcd_vapp:
          vapp_name: "Demo-vapp1"
          vdc: "tststartrek-01"
          network: "tststartrek-VLANabcx"
          network_adapter_type: "VMXNET"
          state: "update"
      when: init is defined
      register: add_network1_vapp
      tags: ['nic1', 'nic' ]
```
When I run it, I get the following error
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: present, absent, got: update"}
```
So I know `state: "update"` does not work, but Ive tried `state: "present"` and it just tells me the vapp already exists. 

Does this functionality exist and Im missing it? Or has anyone found a workable workaround?

Thanks in advance
Ted
