### ISSUE TITLE
raise OperationNotSupportedException from e

### ISSUE THREAD

**Issue by rlambrec** [vmware/ansible-module-vcloud-director#8]
Hi I am getting the following error:
```



The full traceback is: |  
  | 124 | Traceback (most recent call last): |  
  | 125 | File "/tmp/ansible_ZXDt8z/ansible_module_vcd_org.py", line 103, in <module> |  
  | 126 | from pyvcloud.vcd.org import Org |  
  | 127 | File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyvcloud/vcd/org.py", line 27, in <module> |  
  | 128 | from pyvcloud.vcd.acl import Acl |  
  | 129 | File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyvcloud/vcd/acl.py", line 17, in <module> |  
  | 130 | from pyvcloud.vcd.client import E |  
  | 131 | File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyvcloud/vcd/client.py", line 998 |  
  | 132 | raise OperationNotSupportedException from e |  
  | 133 | ^ |  
  | 134 | SyntaxError: invalid syntax |  
  | 135 |   |  
  | 136 | fatal: [127.0.0.1]: FAILED! => { |  
  | 137 | "changed": false, |  
  | 138 | "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZXDt8z/ansible_module_v… |  
  | ...


```

I am using the following yml file:
```
---
- name: test
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: "create org"
    vcd_org:
      org_name: "test_org"
      full_name: "test_org"
      is_enabled : true
      state: present
      user: "{{ vcloud_user }}"
      password: "{{ vcloud_password }}"
      host: "myvcloudurl.org"
```
