### ISSUE TITLE
VM creation not taking the target VM name

### ISSUE THREAD

**Issue by monadhiman** [vmware/ansible-module-vcloud-director#85]
Hi,

I am creating a VM with vcd_vapp_vm and in error message getting this :

line 313, in get_vm\n  File \"/root/.local/lib/python3.6/site-packages/pyvcloud/vcd/vapp.py\", line 633, in get_vm\n    raise EntityNotFoundException('Can\\'t find VM \\'%s\\'' % vm_name)\npyvcloud.vcd.exceptions.EntityNotFoundException: Can't find VM 'new'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n

It is trying to find the VM which I want to create. Could anyone help on this and let me know in case I am doing something wrong here.

Many Thanks in advance.

**Comment by mukultaneja** [comment]
@monadhiman, the module will find if any VM with the same name is already present or not. If not then it will add a new one within the provided Vapp.

**Comment by monadhiman** [comment]
Hi  @mukultaneja 
Thanks for your reply. I was not using the right attribute for the same.
Issue is fixed now, hence closing this one.

Thank You.

**Comment by nirkal** [comment]
@monadhiman May you please write the attribute name here? I've a similar issue.

**Comment by alebeta90** [comment]
Hi @monadhiman I'm facing the same issue. What to you mean with 

> I was not using the right attribute for the same.

It would be helpful to get a solutionn

all the best

**Comment by monadhiman** [comment]
> 
> 
> @monadhiman May you please write the attribute name here? I've a similar issue.

You need to give the hostname as well, Though it says optional but it seems to be a mandatory parameter. In my case, I missed that one and got the above error.

**Comment by monadhiman** [comment]
> 
> 
> Hi @monadhiman I'm facing the same issue. What to you mean with
> 
> > I was not using the right attribute for the same.
> 
> It would be helpful to get a solutionn
> 
> all the best

You need to give the hostname as well, Though it says optional but it seems to be a mandatory parameter. In my case, I missed that one and got the above error.

**Comment by danielc256** [comment]
Someone had an update here?

I'm facing the same issue, but even when I put the hostname (Even doesn't making sense work just because of that), it's not working.

Instead of creating a new VM, it's trying to search one e return with the error message: "Can't find VM"

**Comment by hexpizza** [comment]
Hi @danielc256!
I faced this issue and after a little reading of modules and a few tries I found out that the combination of target_vm_name, hostname and state: "present" works correctly. It looks like that: 

- name: create vapp VM from OVF template
  vcd_vapp_vm:
    verify_ssl_certs: False
    source_catalog_name: "<catalogname>"
    source_template_name: "<template_name>"
    source_vm_name: "<vm_name_inside_template>"
    target_vdc: "vdc"
    target_vapp: "vapp"
    target_vm_name: "ansibletest" 
    hostname: "ansibletest.test.local"
    network: "test_net"
    state: "present"   
    operation: "poweron"

Unexpectedly network parameter is required (at least for me) because if you don`t specify the name it`ll put a "custom" network there (which obviously doesn`t exist).

**Comment by bfanjoy** [comment]
I'm having the same issue with not taking the target_vm_name - I've tried noted fixes but still not working. Any other things to try?

**Comment by hexpizza** [comment]
@bfanjoy I use this list of arguments in the task and it works perfectly:
```
- name: "Create VMware VM {{ vm }}"
  vcd_vapp_vm:
    user: "{{ username }}"
    password: "{{ password }}"
    host: "{{ auth_url }}"
    org: "{{ org }}"
    api_version: 31.0
    verify_ssl_certs: False
    source_catalog_name: "{{ template_catalog }}" 
    source_template_name: "{{ image_name }}"                 
    source_vm_name: "{{ source_vm_name }}"                          
    target_vdc: "{{ vdc }}"
    target_vapp: "{{ vapp }}"
    target_vm_name: "{{ vm }}"
    virtual_cpus: "{{ cpu }}"
    memory: "{{ ram }}"
    hostname: "{{ vm }}"
    network: None
    state: "present"
    operation: "poweron"
```
Sorry for variable names instead of values. 
"target_vm_name" is required argument for the module, look at its source code https://github.com/vmware/ansible-module-vcloud-director/blob/master/modules/vcd_vapp_vm.py strings 55-58.
